language: objective-c
osx_image: xcode8.3
xcode_project: JSONObject.xcodeproj
xcode_scheme: JSONObject
xcode_sdk: iphonesimulator10.3

script:
  - xcodebuild clean build test -project "JSONObject.xcodeproj" -scheme "JSONObject" -destination 'platform=iOS Simulator,id=22FA2149-1241-469C-BF6D-462D3837DB72,OS=10.3'

after_success:
  - bash <(curl -s https://codecov.io/bash)
