language: objective-c
osx_image: xcode8.3
xcode_project: JSONObject.xcodeproj
xcode_scheme: JSONObject
xcode_sdk: macosx10.12

script:
- xcodebuild clean build test -project "JSONObject.xcodeproj" -scheme "JSONObject" -destination 'generic/platform=macOS'

after_success:
- bash <(curl -s https://codecov.io/bash)
